[project]
name = "surveil-the-bulk"
version = "0.1.0"
description = "REST API for advanced Magic: The Gathering collection analysis, wantlist/tradelist management and sharing, and deckbuilding tools."
readme = "README.md"
authors = [
    { name = "Arthur Vieira", email = "arthurssivieira@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
]


[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
